# Generated by Django 5.2.5 on 2025-08-10 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilitie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customar_name', models.CharField(max_length=166)),
                ('memo_number', models.CharField(max_length=20)),
                ('cutomar_phone', models.CharField(max_length=20)),
                ('delivery_address', models.TextField()),
                ('delivery_date', models.DateField()),
                ('frame_show_date', models.DateField()),
                ('order_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utilitie.dealermodel')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utilitie.employeemodel')),
            ],
        ),
    ]
