# Generated by Django 5.2.5 on 2025-10-22 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilitie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=166)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_number', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=266)),
                ('details', models.TextField()),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('delivery_address', models.TextField()),
                ('total_price', models.FloatField(default=0)),
                ('advance_payment', models.FloatField(default=0)),
                ('delivery_date', models.DateField()),
                ('initial_dalivery_date', models.DateField()),
                ('next_advance_payment_date', models.DateField(blank=True, null=True)),
                ('frame_show_date', models.DateField()),
                ('order_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order_management.customermodel')),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utilitie.dealermodel')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utilitie.employeemodel')),
            ],
        ),
    ]
