# Generated by Django 5.2.5 on 2025-12-05 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
        ('utilitie', '0005_customarcomplain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='customar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_management.customermodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilitie.dealermodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilitie.employeemodel'),
        ),
    ]
