# Generated by Django 5.2.5 on 2025-08-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='advance_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='product_image',
            field=models.ImageField(default=1, upload_to='product_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='product_name',
            field=models.CharField(default=1, max_length=266),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
