# Generated by Django 5.2.5 on 2025-08-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=166)),
                ('age', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('dealer_image', models.ImageField(upload_to='dealer_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=166)),
                ('age', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=40)),
                ('join_date', models.DateField()),
                ('performance_status', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('employee_image', models.ImageField(upload_to='dealer_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
