# Generated by Django 5.2.5 on 2025-10-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=166)),
                ('age', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('dealer_image', models.ImageField(upload_to='dealer_image')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nid_number', models.CharField(blank=True, max_length=30, null=True)),
                ('trade_license', models.CharField(blank=True, max_length=50, null=True)),
                ('total_deals', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=166)),
                ('age', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=40)),
                ('join_date', models.DateField()),
                ('performance_status', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('national_id', models.CharField(blank=True, max_length=30, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('leave_days', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('employee_image', models.ImageField(upload_to='dealer_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
