# Generated by Django 5.2.5 on 2025-11-09 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilitie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelaerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_memo', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method', models.CharField(max_length=166)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utilitie.dealermodel')),
            ],
        ),
    ]
