# Generated by Django 5.2.5 on 2025-11-09 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilitie', '0002_delaerpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_title', models.CharField(max_length=100)),
                ('expenses_category', models.CharField(max_length=166)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved_by', models.CharField(max_length=166)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utilitie.employeemodel')),
            ],
        ),
    ]
