# Generated by Django 5.2.5 on 2025-11-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilitie', '0003_employeexpenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomarComplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customar_name', models.CharField(max_length=266)),
                ('title', models.CharField(max_length=366)),
                ('memo', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=366)),
                ('problem_details', models.TextField()),
                ('service_date', models.DateField()),
                ('problem_pic', models.ImageField(upload_to='problemsPic')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
