# Generated by Django 5.2.5 on 2025-11-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilitie', '0004_customarcomplain'),
    ]

    operations = [
        migrations.AddField(
            model_name='customarcomplain',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
