# Generated by Django 5.2.5 on 2025-12-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilitie', '0005_customarcomplain_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='employee_image',
            field=models.ImageField(upload_to='employee_image'),
        ),
    ]
